### PR TITLE
Don't break on chef 15

### LINKED ISSUE #673: gp3 not yet supported although being out for almost a year
# Version:

2.1.4

# Environment:

macOS via CLI

# Scenario:

Trying to create a node with a gp3 root volume 

# Steps to Reproduce:

$ knife ec2 server create (other options) --ebs-volume-type gp3
...
ERROR: --ebs-volume-type must be 'standard' or 'io1' or 'gp2' or 'st1' or 'sc1'

# Expected Result:

It would just create it as normal

# Actual Result:

I get the following error:

ERROR: --ebs-volume-type must be 'standard' or 'io1' or 'gp2' or 'st1' or 'sc1'

### PR DESCRIPTION
**Pull request by betesh-at-data-axle**
The first 2 commits are cherry-picked (and then edited to resolve conflicts) from [the branch](https://github.com/data-axle/knife-ec2/compare/v0.19.16...data-axle:knife-ec2:v0.19.16-da) that we're currently using in [chef-repo](https://github.com/data-axle/chef-repo/blob/c2907e1e492a42496eef9815c4ddadab3062a74c/Gemfile#L9).  They were authored by Peter and appear to be necessary in order to resolve [this issue](https://github.com/chef/knife-ec2/issues/673).

The next 2 commits are mine and are necessary to work with chef 15, i.e. https://github.com/data-axle/chef-repo/pull/525

### CODE REVIEW

**Review by j1wilmot — APPROVED** [review]
Nice, will be good to get to v15. Pretty surprising this issue hasn't been fixed upstream.

File: lib/chef/knife/ec2_server_create.rb [hunk 1]
```diff
@@ -682,8 +683,9 @@ def plugin_validate_options!
           # validation for ebs_size and ebs_volume_type and ebs_encrypted
           if !config[:ebs_size]
             errors << "--ebs-encrypted option requires valid --ebs-size to be specified."
-          elsif (config[:ebs_volume_type] == "gp2") && ! config[:ebs_size].to_i.between?(1, 16384)
-            errors << "--ebs-size should be in between 1-16384 for 'gp2' ebs volume type."
+
```
Comment (matthinea) [inline lib/chef/knife/ec2_server_create.rb:686]: whitespace?

Comment (matthinea) [reply lib/chef/knife/ec2_server_create.rb:686]: Oh this is merged, forget it
